[tool.coverage.run]
branch = true

[tool.coverage.report]
fail_under = 100
show_missing = true
omit = [
  "nlp_profilfer/__init__.py",
  "tests/__init__.py",
  "tests/*/__init__.py",
]
exclude_lines = ["pragma: no cover", "raise NotImplementedError", "pass"]
